/**
 * LaTeX command snippets for autocomplete. Trigger is what the user types after \;
 * snippet is inserted and cursor placed in first {} if present.
 */
export const LATEX_SNIPPETS: { trigger: string; snippet: string }[] = [
  { trigger: '\\frac', snippet: '\\frac{}{}' },
  { trigger: '\\sqrt', snippet: '\\sqrt{}' },
  { trigger: '\\sum', snippet: '\\sum_{}^{}' },
  { trigger: '\\int', snippet: '\\int_{}^{}' },
  { trigger: '\\lim', snippet: '\\lim_{ \\to }' },
  { trigger: '\\binom', snippet: '\\binom{}{}' },
  { trigger: '\\overline', snippet: '\\overline{}' },
  { trigger: '\\underline', snippet: '\\underline{}' },
  { trigger: '\\overrightarrow', snippet: '\\overrightarrow{}' },
  { trigger: '\\hat', snippet: '\\hat{}' },
  { trigger: '\\bar', snippet: '\\bar{}' },
  { trigger: '\\vec', snippet: '\\vec{}' },
  { trigger: '\\dot', snippet: '\\dot{}' },
  { trigger: '\\ddot', snippet: '\\ddot{}' },
  { trigger: '\\log', snippet: '\\log' },
  { trigger: '\\ln', snippet: '\\ln' },
  { trigger: '\\sin', snippet: '\\sin' },
  { trigger: '\\cos', snippet: '\\cos' },
  { trigger: '\\tan', snippet: '\\tan' },
  { trigger: '\\sec', snippet: '\\sec' },
  { trigger: '\\csc', snippet: '\\csc' },
  { trigger: '\\cot', snippet: '\\cot' },
  { trigger: '\\arcsin', snippet: '\\arcsin' },
  { trigger: '\\arccos', snippet: '\\arccos' },
  { trigger: '\\arctan', snippet: '\\arctan' },
  { trigger: '\\exp', snippet: '\\exp' },
  { trigger: '\\alpha', snippet: '\\alpha' },
  { trigger: '\\beta', snippet: '\\beta' },
  { trigger: '\\gamma', snippet: '\\gamma' },
  { trigger: '\\delta', snippet: '\\delta' },
  { trigger: '\\epsilon', snippet: '\\epsilon' },
  { trigger: '\\theta', snippet: '\\theta' },
  { trigger: '\\lambda', snippet: '\\lambda' },
  { trigger: '\\mu', snippet: '\\mu' },
  { trigger: '\\pi', snippet: '\\pi' },
  { trigger: '\\sigma', snippet: '\\sigma' },
  { trigger: '\\phi', snippet: '\\phi' },
  { trigger: '\\omega', snippet: '\\omega' },
  { trigger: '\\infty', snippet: '\\infty' },
  { trigger: '\\partial', snippet: '\\partial' },
  { trigger: '\\times', snippet: '\\times' },
  { trigger: '\\cdot', snippet: '\\cdot' },
  { trigger: '\\pm', snippet: '\\pm' },
  { trigger: '\\mp', snippet: '\\mp' },
  { trigger: '\\leq', snippet: '\\leq' },
  { trigger: '\\geq', snippet: '\\geq' },
  { trigger: '\\neq', snippet: '\\neq' },
  { trigger: '\\approx', snippet: '\\approx' },
  { trigger: '\\equiv', snippet: '\\equiv' },
  { trigger: '\\to', snippet: '\\to' },
  { trigger: '\\rightarrow', snippet: '\\rightarrow' },
  { trigger: '\\leftarrow', snippet: '\\leftarrow' },
  { trigger: '\\Rightarrow', snippet: '\\Rightarrow' },
  { trigger: '\\Leftarrow', snippet: '\\Leftarrow' },
  { trigger: '\\in', snippet: '\\in' },
  { trigger: '\\notin', snippet: '\\notin' },
  { trigger: '\\subset', snippet: '\\subset' },
  { trigger: '\\subseteq', snippet: '\\subseteq' },
  { trigger: '\\cup', snippet: '\\cup' },
  { trigger: '\\cap', snippet: '\\cap' },
  { trigger: '\\forall', snippet: '\\forall' },
  { trigger: '\\exists', snippet: '\\exists' },
  { trigger: '\\neg', snippet: '\\neg' },
  { trigger: '\\text', snippet: '\\text{}' },
  { trigger: '\\begin', snippet: '\\begin{}' },
  { trigger: '\\end', snippet: '\\end{}' },
  { trigger: '\\left', snippet: '\\left' },
  { trigger: '\\right', snippet: '\\right' },
  { trigger: '\\big', snippet: '\\big' },
  { trigger: '\\Big', snippet: '\\Big' },
  { trigger: '\\bigg', snippet: '\\bigg' },
  { trigger: '\\Bigg', snippet: '\\Bigg' },
];

const SORTED = [...LATEX_SNIPPETS].sort((a, b) => a.trigger.localeCompare(b.trigger));

export function filterLatexCompletions(fragment: string): { trigger: string; snippet: string }[] {
  if (!fragment || !fragment.startsWith('\\')) return [];
  const lower = fragment.toLowerCase();
  return SORTED.filter((s) => s.trigger.toLowerCase().startsWith(lower)).slice(0, 10);
}
